# Generated by Django 5.1.4 on 2025-01-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_salesorder_user'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='product',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
