# Generated by Django 5.1.4 on 2025-01-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_salesorder_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='product',
            new_name='products',
        ),
    ]
